-- Shule AI v21 Render hotfix
-- Fixes: column "schoolId" does not exist while creating TutorMessages index.
-- Safe to run more than once.

CREATE TABLE IF NOT EXISTS "TutorSessions" (
  "id" SERIAL PRIMARY KEY,
  "schoolId" VARCHAR(255) NOT NULL DEFAULT 'default-school',
  "studentId" INTEGER NOT NULL DEFAULT 0,
  "userId" INTEGER,
  "grade" VARCHAR(255),
  "level" VARCHAR(255),
  "subject" VARCHAR(255),
  "mode" VARCHAR(255) NOT NULL DEFAULT 'learn',
  "lastCommand" VARCHAR(255),
  "metadata" JSONB DEFAULT '{}'::jsonb,
  "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "TutorMessages" (
  "id" SERIAL PRIMARY KEY,
  "schoolId" VARCHAR(255) NOT NULL DEFAULT 'default-school',
  "sessionId" INTEGER,
  "studentId" INTEGER NOT NULL DEFAULT 0,
  "userId" INTEGER,
  "role" VARCHAR(255) NOT NULL DEFAULT 'student',
  "message" TEXT NOT NULL DEFAULT '',
  "subject" VARCHAR(255),
  "topic" VARCHAR(255),
  "command" VARCHAR(255),
  "source" VARCHAR(255),
  "metadata" JSONB DEFAULT '{}'::jsonb,
  "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "TutorProgresses" (
  "id" SERIAL PRIMARY KEY,
  "schoolId" VARCHAR(255) NOT NULL DEFAULT 'default-school',
  "studentId" INTEGER NOT NULL DEFAULT 0,
  "grade" VARCHAR(255),
  "level" VARCHAR(255),
  "subject" VARCHAR(255) NOT NULL DEFAULT 'General',
  "topic" VARCHAR(255) NOT NULL DEFAULT 'General',
  "attempts" INTEGER DEFAULT 0,
  "correct" INTEGER DEFAULT 0,
  "lastCommand" VARCHAR(255),
  "lastSource" VARCHAR(255),
  "lastStudiedAt" TIMESTAMP WITH TIME ZONE,
  "metadata" JSONB DEFAULT '{}'::jsonb,
  "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "TutorUsages" (
  "id" SERIAL PRIMARY KEY,
  "schoolId" VARCHAR(255) NOT NULL DEFAULT 'default-school',
  "studentId" INTEGER NOT NULL DEFAULT 0,
  "usageDate" DATE NOT NULL DEFAULT CURRENT_DATE,
  "totalQuestions" INTEGER DEFAULT 0,
  "aiCalls" INTEGER DEFAULT 0,
  "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

ALTER TABLE "TutorSessions" ADD COLUMN IF NOT EXISTS "schoolId" VARCHAR(255) NOT NULL DEFAULT 'default-school';
ALTER TABLE "TutorSessions" ADD COLUMN IF NOT EXISTS "studentId" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "TutorSessions" ADD COLUMN IF NOT EXISTS "userId" INTEGER;
ALTER TABLE "TutorSessions" ADD COLUMN IF NOT EXISTS "grade" VARCHAR(255);
ALTER TABLE "TutorSessions" ADD COLUMN IF NOT EXISTS "level" VARCHAR(255);
ALTER TABLE "TutorSessions" ADD COLUMN IF NOT EXISTS "subject" VARCHAR(255);
ALTER TABLE "TutorSessions" ADD COLUMN IF NOT EXISTS "mode" VARCHAR(255) NOT NULL DEFAULT 'learn';
ALTER TABLE "TutorSessions" ADD COLUMN IF NOT EXISTS "lastCommand" VARCHAR(255);
ALTER TABLE "TutorSessions" ADD COLUMN IF NOT EXISTS "metadata" JSONB DEFAULT '{}'::jsonb;
ALTER TABLE "TutorSessions" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();
ALTER TABLE "TutorSessions" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();

ALTER TABLE "TutorMessages" ADD COLUMN IF NOT EXISTS "schoolId" VARCHAR(255) NOT NULL DEFAULT 'default-school';
ALTER TABLE "TutorMessages" ADD COLUMN IF NOT EXISTS "sessionId" INTEGER;
ALTER TABLE "TutorMessages" ADD COLUMN IF NOT EXISTS "studentId" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "TutorMessages" ADD COLUMN IF NOT EXISTS "userId" INTEGER;
ALTER TABLE "TutorMessages" ADD COLUMN IF NOT EXISTS "role" VARCHAR(255) NOT NULL DEFAULT 'student';
ALTER TABLE "TutorMessages" ADD COLUMN IF NOT EXISTS "message" TEXT NOT NULL DEFAULT '';
ALTER TABLE "TutorMessages" ADD COLUMN IF NOT EXISTS "subject" VARCHAR(255);
ALTER TABLE "TutorMessages" ADD COLUMN IF NOT EXISTS "topic" VARCHAR(255);
ALTER TABLE "TutorMessages" ADD COLUMN IF NOT EXISTS "command" VARCHAR(255);
ALTER TABLE "TutorMessages" ADD COLUMN IF NOT EXISTS "source" VARCHAR(255);
ALTER TABLE "TutorMessages" ADD COLUMN IF NOT EXISTS "metadata" JSONB DEFAULT '{}'::jsonb;
ALTER TABLE "TutorMessages" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();
ALTER TABLE "TutorMessages" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();

ALTER TABLE "TutorProgresses" ADD COLUMN IF NOT EXISTS "schoolId" VARCHAR(255) NOT NULL DEFAULT 'default-school';
ALTER TABLE "TutorProgresses" ADD COLUMN IF NOT EXISTS "studentId" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "TutorProgresses" ADD COLUMN IF NOT EXISTS "grade" VARCHAR(255);
ALTER TABLE "TutorProgresses" ADD COLUMN IF NOT EXISTS "level" VARCHAR(255);
ALTER TABLE "TutorProgresses" ADD COLUMN IF NOT EXISTS "subject" VARCHAR(255) NOT NULL DEFAULT 'General';
ALTER TABLE "TutorProgresses" ADD COLUMN IF NOT EXISTS "topic" VARCHAR(255) NOT NULL DEFAULT 'General';
ALTER TABLE "TutorProgresses" ADD COLUMN IF NOT EXISTS "attempts" INTEGER DEFAULT 0;
ALTER TABLE "TutorProgresses" ADD COLUMN IF NOT EXISTS "correct" INTEGER DEFAULT 0;
ALTER TABLE "TutorProgresses" ADD COLUMN IF NOT EXISTS "lastCommand" VARCHAR(255);
ALTER TABLE "TutorProgresses" ADD COLUMN IF NOT EXISTS "lastSource" VARCHAR(255);
ALTER TABLE "TutorProgresses" ADD COLUMN IF NOT EXISTS "lastStudiedAt" TIMESTAMP WITH TIME ZONE;
ALTER TABLE "TutorProgresses" ADD COLUMN IF NOT EXISTS "metadata" JSONB DEFAULT '{}'::jsonb;
ALTER TABLE "TutorProgresses" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();
ALTER TABLE "TutorProgresses" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();

ALTER TABLE "TutorUsages" ADD COLUMN IF NOT EXISTS "schoolId" VARCHAR(255) NOT NULL DEFAULT 'default-school';
ALTER TABLE "TutorUsages" ADD COLUMN IF NOT EXISTS "studentId" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "TutorUsages" ADD COLUMN IF NOT EXISTS "usageDate" DATE NOT NULL DEFAULT CURRENT_DATE;
ALTER TABLE "TutorUsages" ADD COLUMN IF NOT EXISTS "totalQuestions" INTEGER DEFAULT 0;
ALTER TABLE "TutorUsages" ADD COLUMN IF NOT EXISTS "aiCalls" INTEGER DEFAULT 0;
ALTER TABLE "TutorUsages" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();
ALTER TABLE "TutorUsages" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();

CREATE INDEX IF NOT EXISTS idx_tutor_messages_school_student_created
ON "TutorMessages" ("schoolId", "studentId", "createdAt");

CREATE UNIQUE INDEX IF NOT EXISTS idx_tutor_progress_school_student_subject_topic
ON "TutorProgresses" ("schoolId", "studentId", "subject", "topic");

CREATE UNIQUE INDEX IF NOT EXISTS idx_tutor_usage_school_student_date
ON "TutorUsages" ("schoolId", "studentId", "usageDate");
