-- Shule AI V5 targeted recovery hotfix.
-- Safe to run more than once.

ALTER TABLE "Users" ALTER COLUMN "schoolCode" DROP NOT NULL;
UPDATE "Users" SET "schoolCode" = NULL WHERE "role" = 'super_admin' AND "schoolCode" = 'SUPER-ADMIN';

ALTER TABLE "Students" ADD COLUMN IF NOT EXISTS "assessmentNumber" VARCHAR(255);
ALTER TABLE "Students" ADD COLUMN IF NOT EXISTS "nemisNumber" VARCHAR(255);
ALTER TABLE "Students" ADD COLUMN IF NOT EXISTS "location" VARCHAR(255);
ALTER TABLE "Students" ADD COLUMN IF NOT EXISTS "parentName" VARCHAR(255);
ALTER TABLE "Students" ADD COLUMN IF NOT EXISTS "parentEmail" VARCHAR(255);
ALTER TABLE "Students" ADD COLUMN IF NOT EXISTS "parentPhone" VARCHAR(255);
ALTER TABLE "Students" ADD COLUMN IF NOT EXISTS "parentRelationship" VARCHAR(255) DEFAULT 'guardian';
ALTER TABLE "Students" ADD COLUMN IF NOT EXISTS "isPrefect" BOOLEAN DEFAULT false;

ALTER TABLE "SchoolCalendars" ADD COLUMN IF NOT EXISTS "term" VARCHAR(255);
ALTER TABLE "SchoolCalendars" ADD COLUMN IF NOT EXISTS "year" INTEGER;
ALTER TABLE "SchoolCalendars" ADD COLUMN IF NOT EXISTS "description" TEXT;

ALTER TABLE "Timetables" ADD COLUMN IF NOT EXISTS "term" VARCHAR(255);
ALTER TABLE "Timetables" ADD COLUMN IF NOT EXISTS "year" INTEGER;
ALTER TABLE "Timetables" ADD COLUMN IF NOT EXISTS "scope" VARCHAR(255) DEFAULT 'term';
ALTER TABLE "Timetables" ADD COLUMN IF NOT EXISTS "classes" JSONB DEFAULT '[]'::jsonb;
ALTER TABLE "Timetables" ADD COLUMN IF NOT EXISTS "warnings" JSONB DEFAULT '[]'::jsonb;

ALTER TABLE "HomeTasks" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE "HomeTasks" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE "HomeTaskAssignments" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE "HomeTaskAssignments" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE "MoodCheckins" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE "MoodCheckins" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE "Badges" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE "Badges" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE "Rewards" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE "Rewards" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE "StudentBadges" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE "StudentBadges" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE "StudentRewards" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE "StudentRewards" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMPTZ DEFAULT NOW();